name: rupio
description: "A clean architecture Flutter application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.0.3

  # Networking
  http: ^1.2.2

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/splash/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/splash/rupio-logo.png"
  adaptive_icon_background: "#0D0D0D"
  adaptive_icon_foreground: "assets/splash/rupio-logo.png"

flutter_native_splash:
  color: "#0D0D0D"
  image: assets/splash/rupio-logo.png
  android_12:
    color: "#0D0D0D"
    image: assets/splash/rupio-logo.png
